CREATE UNIQUE INDEX IF NOT EXISTS I_PARTNER_LEGAL_NAME ON partner(legal_name);

CREATE INDEX IF NOT EXISTS I_PARTNER_CONTACT_CONTACT_NAME ON partner_contact(PARTNER_ID,CONTACT_PERSON_NAME);

CREATE UNIQUE INDEX IF NOT EXISTS UI_DEPOSIT_BOX_NAME ON deposit_box(name);

CREATE UNIQUE INDEX IF NOT EXISTS UI_EXPENSE_DOCUMENT_NO ON expense(partner_id, document_no);

CREATE UNIQUE INDEX IF NOT EXISTS UI_INCOME_DOCUMENT_NO ON income(partner_id, document_no);

CREATE INDEX IF NOT EXISTS I_EXPENSE_DETAIL_EXPENSE_ID ON expense_detail(expense_id);

CREATE INDEX IF NOT EXISTS I_INCOME_DETAIL_INCOME_ID ON income_detail(income_id);

CREATE INDEX IF NOT EXISTS I_DEPOSIT_BOX_X_INCOME_INCOME_ID ON DEPOSIT_BOX_X_INCOME(DEPOSIT_BOX_ID,INCOME_ID);

CREATE INDEX IF NOT EXISTS I_DEPOSIT_BOX_X_EXPENSE_EXPENSE_ID ON DEPOSIT_BOX_X_EXPENSE(DEPOSIT_BOX_ID,EXPENSE_ID);
