--TRX
CREATE TABLE PARTNER
(
  PARTNER_ID SERIAL NOT NULL,
  LEGAL_NAME VARCHAR(100) NOT NULL,
  SHORT_NAME VARCHAR(50),
  BANK_ACCOUNT_NO VARCHAR(30),
  LEGAL_ADDRESS VARCHAR(200),
  TAX_ID_NO VARCHAR(50),
  VALD_FROM_DTTM DATE NOT NULL,
  VALID_TO_DTTM DATE NOT NULL,
  MODIFICAITON_STATUS_CD BOOL NOT NULL,
  PRIMARY KEY (PARTNER_ID),
  UNIQUE (LEGAL_NAME)
);

CREATE TABLE PARTNER_CONTACT
(
  PARTNER_CONTACT_ID SERIAL NOT NULL,
  CONTACT_PERSON_NAME VARCHAR(50) NOT NULL,
  PHONE_NO VARCHAR(50),
  EMAIL_ADDR VARCHAR(253),
  CELL_PHONE_NO VARCHAR(50),
  PARTNER_ID INTEGER NOT NULL,
  PRIMARY KEY (PARTNER_CONTACT_ID),
  FOREIGN KEY (PARTNER_ID) REFERENCES PARTNER(PARTNER_ID)
);

CREATE TABLE DOCUMENT_TYPE
(
  DOCUMENT_TYPE_ID SERIAL NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  DOCUMENT_TYPE_TYPE_CD INTEGER NOT NULL,
  DESCRIPTION_TXT VARCHAR(500),
  VALID_FROM_DTTM DATE NOT NULL,
  VALID_TO_DTTM DATE NOT NULL,
  MODIFICATION_STATUS_CD BOOL NOT NULL,
  PRIMARY KEY (DOCUMENT_TYPE_ID),
  UNIQUE (NAME)
);

CREATE TABLE PAYMENT_METHOD
(
  PAYMENT_METHOD_ID SERIAL NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  PAYMENT_METHOD_TYPE_CD INTEGER NOT NULL,
  DESCRIPTION_TXT VARCHAR(500),
  VALID_FROM_DTTM DATE NOT NULL,
  VALID_TO_DTTM DATE NOT NULL,
  MODIFICATION_STATUS_CD BOOL NOT NULL,
  PRIMARY KEY (PAYMENT_METHOD_ID),
  UNIQUE (NAME)
);

CREATE TABLE COST_CENTER
(
  COST_CENTER_ID SERIAL NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION_TXT VARCHAR(500),
  PARENT_COST_CENTER_ID INTEGER,
  VALID_FROM_DTTM DATE NOT NULL,
  VALID_TO_DTTM DATE NOT NULL,
  MODIFICAITON_STATUS_CD BOOL NOT NULL,
  PRIMARY KEY (COST_CENTER_ID),
  UNIQUE (NAME)
);

CREATE TABLE COST_TYPE
(
  COST_TYPE_ID SERIAL NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION_TXT VARCHAR(500),
  VALID_FROM_DTTM DATE NOT NULL,
  VALID_TO_DTTM DATE NOT NULL,
  MODIFICATION_STATUS_CD BOOL NOT NULL,
  PRIMARY KEY (COST_TYPE_ID),
  UNIQUE (NAME)
);

CREATE TABLE INCOME_TYPE
(
  INCOME_TYPE_ID SERIAL NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  VALID_FROM_DTTM DATE NOT NULL,
  VALID_TO_DTTM DATE NOT NULL,
  DESCRIPTION_TXT VARCHAR(500),
  MODIFICATION_STATUS_CD BOOL NOT NULL,
  PRIMARY KEY (INCOME_TYPE_ID),
  UNIQUE (NAME)
);

CREATE TABLE DEPOSIT_BOX
(
  DEPOSIT_BOX_ID SERIAL NOT NULL,
  DEPOSIT_BOX_TYPE_CD INTEGER NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION_TXT VARCHAR(500) NOT NULL,
  PRIMARY KEY (DEPOSIT_BOX_ID),
  UNIQUE (NAME)
);

CREATE TABLE PARAM_ALLOWED_PAYMENT_X_DEPOSIT
(
  ALLOWED_PAYMENT_X_DEPOSIT_BOX_ID SERIAL NOT NULL,
  VALID_FROM_DTTM DATE NOT NULL,
  VALID_TO_DTTM DATE NOT NULL,
  DEFAULT_DEPOSIT_FLG BOOL NOT NULL,
  DEPOSIT_BOX_ID INTEGER NOT NULL,
  PAYMENT_METHOD_ID INTEGER NOT NULL,
  MODIFICATION_STATUS_CD BOOL NOT NULL,
  PRIMARY KEY (ALLOWED_PAYMENT_X_DEPOSIT_BOX_ID)
);

CREATE TABLE RO_USER
(
  USER_ID SERIAL NOT NULL,
  PRIMARY KEY (USER_ID)
);

CREATE TABLE TRANSITION
(
  TRANSITION_ID SERIAL NOT NULL,
  TRANSITION_DTTM DATE NOT NULL,
  TRANSITION_AMT NUMERIC(12,2) NOT NULL,
  FROM_DEPOSIT_BOX_ID INTEGER NOT NULL,
  TO_DEPOSIT_BOX_ID INTEGER NOT NULL,
  USER_ID INTEGER NOT NULL,
  PRIMARY KEY (TRANSITION_ID),
  FOREIGN KEY (FROM_DEPOSIT_BOX_ID) REFERENCES DEPOSIT_BOX(DEPOSIT_BOX_ID),
  FOREIGN KEY (TO_DEPOSIT_BOX_ID) REFERENCES DEPOSIT_BOX(DEPOSIT_BOX_ID),
  FOREIGN KEY (USER_ID) REFERENCES RO_USER(USER_ID)
);

CREATE TABLE PAYMENT_DETAIL
(
  PAYMENT_DETAIL_ID SERIAL NOT NULL,
  ISSUE_DT DATE NOT NULL,
  DUE_DT DATE NOT NULL,
  EXPIRY_DT DATE,
  PAID_DT DATE,
  DOCUMENT_TYPE_ID INTEGER NOT NULL,
  PAYMENT_METHOD_ID INTEGER NOT NULL,
  PRIMARY KEY (PAYMENT_DETAIL_ID),
  FOREIGN KEY (DOCUMENT_TYPE_ID) REFERENCES DOCUMENT_TYPE(DOCUMENT_TYPE_ID),
  FOREIGN KEY (PAYMENT_METHOD_ID) REFERENCES PAYMENT_METHOD(PAYMENT_METHOD_ID)
);

CREATE TABLE EXPENSE
(
  EXPENSE_ID SERIAL NOT NULL,
  DOCUMENT_NO VARCHAR(50) NOT NULL,
  PARTNER_ID INTEGER NOT NULL,
  PAYMENT_DETAIL_ID INTEGER NOT NULL,
  CREATE_DTTM DATE NOT NULL,
  DELETE_DTTM DATE,
  CREATE_USER_ID INTEGER NOT NULL,
  DELETE_USER_ID INTEGER,
  PRIMARY KEY (EXPENSE_ID),
  FOREIGN KEY (PARTNER_ID) REFERENCES PARTNER(PARTNER_ID),
  FOREIGN KEY (PAYMENT_DETAIL_ID) REFERENCES PAYMENT_DETAIL(PAYMENT_DETAIL_ID),
  FOREIGN KEY (CREATE_USER_ID) REFERENCES RO_USER(USER_ID),
  FOREIGN KEY (DELETE_USER_ID) REFERENCES RO_USER(USER_ID),
  UNIQUE (DOCUMENT_NO)
);

CREATE TABLE EXPENSE_DETAIL
(
  EXPENSE_DETAIL_ID SERIAL NOT NULL,
  EXPENSE_NET_AMT NUMERIC(12,2),
  EXPENSE_GROSS_AMT NUMERIC(12,2) NOT NULL,
  EXPENSE_VAT_PCT NUMERIC(2,2),
  DESCRIPTION_TXT VARCHAR(500) NOT NULL,
  COST_TYPE_ID INTEGER NOT NULL,
  COST_CENTER_ID INTEGER NOT NULL,
  EXPENSE_ID INTEGER NOT NULL,
  PRIMARY KEY (EXPENSE_DETAIL_ID),
  FOREIGN KEY (COST_TYPE_ID) REFERENCES COST_TYPE(COST_TYPE_ID),
  FOREIGN KEY (COST_CENTER_ID) REFERENCES COST_CENTER(COST_CENTER_ID),
  FOREIGN KEY (EXPENSE_ID) REFERENCES EXPENSE(EXPENSE_ID)
);

CREATE TABLE INCOME
(
  INCOME_ID SERIAL NOT NULL,
  DOCUMENT_NO VARCHAR(50) NOT NULL,
  PAYMENT_DETAIL_ID INTEGER NOT NULL,
  PARTNER_ID INTEGER NOT NULL,
  CREATE_DTTM DATE NOT NULL,
  DELETED_DTTM DATE,
  CREATE_USER_ID INTEGER NOT NULL,
  DELETE_USER_ID INTEGER,
  PRIMARY KEY (INCOME_ID),
  FOREIGN KEY (CREATE_USER_ID) REFERENCES RO_USER(USER_ID),
  FOREIGN KEY (DELETE_USER_ID) REFERENCES RO_USER(USER_ID),
  FOREIGN KEY (PAYMENT_DETAIL_ID) REFERENCES PAYMENT_DETAIL(PAYMENT_DETAIL_ID),
  FOREIGN KEY (PARTNER_ID) REFERENCES PARTNER(PARTNER_ID),
  UNIQUE (DOCUMENT_NO)
);

CREATE TABLE INCOME_DETAIL
(
  INCOME_DETAIL_ID SERIAL NOT NULL,
  INCOME_NET_AMT NUMERIC(12,2),
  INCOME_GROSS_AMT NUMERIC(12,2) NOT NULL,
  INCOME_VAT_PCT NUMERIC(2,2),
  DESCRIPTION_TXT VARCHAR(500) NOT NULL,
  INCOME_ID INTEGER NOT NULL,
  INCOME_TYPE_ID INTEGER NOT NULL,
  PRIMARY KEY (INCOME_DETAIL_ID),
  FOREIGN KEY (INCOME_ID) REFERENCES INCOME(INCOME_ID),
  FOREIGN KEY (INCOME_TYPE_ID) REFERENCES INCOME_TYPE(INCOME_TYPE_ID)
);

CREATE TABLE DEPOSIT_BOX_X_INCOME
(
  DEPOSIT_BOX_X_INCOME_ID SERIAL NOT NULL,
  REGISTERED_DTTM DATE NOT NULL,
  DEPOSIT_BOX_ID INTEGER NOT NULL,
  INCOME_ID INTEGER NOT NULL,
  PRIMARY KEY (DEPOSIT_BOX_X_INCOME_ID),
  FOREIGN KEY (DEPOSIT_BOX_ID) REFERENCES DEPOSIT_BOX(DEPOSIT_BOX_ID),
  FOREIGN KEY (INCOME_ID) REFERENCES INCOME(INCOME_ID)
);

CREATE TABLE DEPOSIT_BOX_X_EXPENSE
(
  DEPOSIT_BOX_X_EXPENSE_ID SERIAL NOT NULL,
  REGISTERED_DTTM DATE NOT NULL,
  DEPOSIT_BOX_ID INTEGER NOT NULL,
  EXPENSE_ID INTEGER NOT NULL,
  PRIMARY KEY (DEPOSIT_BOX_X_EXPENSE_ID),
  FOREIGN KEY (DEPOSIT_BOX_ID) REFERENCES DEPOSIT_BOX(DEPOSIT_BOX_ID),
  FOREIGN KEY (EXPENSE_ID) REFERENCES EXPENSE(EXPENSE_ID)
);
--DAILY TRX
CREATE TABLE JOB_TYPE
(
  JOB_TYPE_ID SERIAL NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  JOB_HOURLY_WAGE_AMT NUMERIC(12,2) NOT NULL,
  JOB_TIP_SHARE_PCT NUMERIC(2,2) NOT NULL,
  DESCRIPTION_TXT VARCHAR(500),
  VALID_FROM_DTTM DATE NOT NULL,
  VALID_TO_DTTM DATE NOT NULL,
  MODIFICATION_STATUS_CD BOOL NOT NULL,
  PRIMARY KEY (JOB_TYPE_ID),
  UNIQUE (NAME)
);

CREATE TABLE INCOME_FORM_TYPE
(
  INCOME_FORM_TYPE_ID SERIAL NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION_TXT VARCHAR(500) NOT NULL,
  VALID_FROM_DTTM DATE NOT NULL,
  VALID_TO_DTTM DATE NOT NULL,
  MODIFICATION_STATUS_CD BOOL NOT NULL,
  PRIMARY KEY (INCOME_FORM_TYPE_ID),
  UNIQUE (NAME)
);

CREATE TABLE REGISTER_TYPE
(
  REGISTER_TYPE_ID SERIAL NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION_TXT VARCHAR(500),
  VALID_FROM_DTTM DATE NOT NULL,
  VALID_TO_DTTM DATE NOT NULL,
  MODIFICATION_STATUS_CD BOOL NOT NULL,
  PRIMARY KEY (REGISTER_TYPE_ID),
  UNIQUE (NAME)
);

CREATE TABLE PARAM_INCOME_FORM_X_DEPOSIT_BOX
(
  INCOME_FORM_X_DEPOSIT_BOX_ID SERIAL NOT NULL,
  VALID_FROM_DTTM DATE NOT NULL,
  VALID_TO_DTTM DATE NOT NULL,
  MODIFICATION_STATUS_CD BOOL NOT NULL,
  DEPOSIT_BOX_ID INTEGER NOT NULL,
  INCOME_FORM_ID INTEGER NOT NULL,
  PRIMARY KEY (INCOME_FORM_X_DEPOSIT_BOX_ID)
);

CREATE TABLE EMPLOYEE
(
  NAME VARCHAR(50) NOT NULL,
  EMPLOYEE_HORULY_WAGE_AMT NUMERIC(12,2),
  EMPLOYEE_TIP_SHARE_PCT NUMERIC(2,2),
  EMPLOYEE_ID SERIAL NOT NULL,
  VALID_FROM_DTTM DATE NOT NULL,
  VALID_TO_DTTM DATE NOT NULL,
  MODIFICATION_STATUS_CD BOOL NOT NULL,
  JOB_TYPE_ID INTEGER NOT NULL,
  PRIMARY KEY (EMPLOYEE_ID),
  FOREIGN KEY (JOB_TYPE_ID) REFERENCES JOB_TYPE(JOB_TYPE_ID)
);

CREATE TABLE REGISTER
(
  REGISTER_ID SERIAL NOT NULL,
  REGISTER_NO VARCHAR(50) NOT NULL,
  VALID_FROM_DTTM DATE NOT NULL,
  VALID_TO_DTTM DATE NOT NULL,
  MODIFICATION_STATUS_CD BOOL NOT NULL,
  REGISTER_TYPE_ID INTEGER NOT NULL,
  PRIMARY KEY (REGISTER_ID),
  FOREIGN KEY (REGISTER_TYPE_ID) REFERENCES REGISTER_TYPE(REGISTER_TYPE_ID),
  UNIQUE (REGISTER_NO)
);

CREATE TABLE DAILY_CLOSE
(
  DAILY_CLOSE_ID SERIAL NOT NULL,
  CLOSE_DAY_DT DATE NOT NULL,
  POS_TOTAL_AMT NUMERIC(12,2) NOT NULL,
  CASH_REGISTER_TOTAL_AMT NUMERIC(12,2) NOT NULL,
  INCOME_TOTAL_AMT NUMERIC(12,2) NOT NULL,
  CREATE_DTTM DATE NOT NULL,
  BOOKED_DTTM DATE,
  CREATE_USER_ID INTEGER,
  BOOKED_USER_ID INTEGER,
  PRIMARY KEY (DAILY_CLOSE_ID),
  FOREIGN KEY (CREATE_USER_ID) REFERENCES RO_USER(USER_ID),
  FOREIGN KEY (BOOKED_USER_ID) REFERENCES RO_USER(USER_ID)
);

CREATE TABLE DAILY_CLOSE_DETAIL
(
  DAILY_CLOSE_DETAIL_ID SERIAL NOT NULL,
  IN_REGISTER_FLG BOOL NOT NULL,
  INCOME_AMT NUMERIC(12,2) NOT NULL,
  DAILY_CLOSE_ID INTEGER NOT NULL,
  INCOME_ID INTEGER,
  INCOME_FORM_TYPE_ID INTEGER NOT NULL,
  PRIMARY KEY (DAILY_CLOSE_DETAIL_ID),
  FOREIGN KEY (DAILY_CLOSE_ID) REFERENCES DAILY_CLOSE(DAILY_CLOSE_ID),
  FOREIGN KEY (INCOME_ID) REFERENCES INCOME(INCOME_ID),
  FOREIGN KEY (INCOME_FORM_TYPE_ID) REFERENCES INCOME_FORM_TYPE(INCOME_FORM_TYPE_ID),
  UNIQUE (DAILY_CLOSE_ID, INCOME_FORM_TYPE_ID)
);

CREATE TABLE REGISTER_CLOSE
(
  REGISTER_CLOSE_ID SERIAL NOT NULL,
  CLOSE_NO INT NOT NULL,
  CLOSE_DT DATE NOT NULL,
  CLOSE_AMT NUMERIC(12,2) NOT NULL,
  CREATE_DTTM DATE NOT NULL,
  REGISTER_ID INTEGER NOT NULL,
  DAILY_CLOSE_ID INTEGER,
  CREATE_USER_ID INTEGER NOT NULL,
  PRIMARY KEY (REGISTER_CLOSE_ID),
  FOREIGN KEY (REGISTER_ID) REFERENCES REGISTER(REGISTER_ID),
  FOREIGN KEY (DAILY_CLOSE_ID) REFERENCES DAILY_CLOSE(DAILY_CLOSE_ID),
  FOREIGN KEY (CREATE_USER_ID) REFERENCES RO_USER(USER_ID),
  UNIQUE (CLOSE_NO, REGISTER_ID)
);

CREATE TABLE EMPLOYEE_SHIFT
(
  EMPLOYEE_SHIFT_ID SERIAL NOT NULL,
  START_DTTM DATE NOT NULL,
  END_DTTM DATE NOT NULL,
  POS_INCOME_AMT NUMERIC(12,2) NOT NULL,
  ACTUAL_HOURLY_WAGE NUMERIC(12,2),
  ACTUAL_TIP_SHARE_PCT NUMERIC(2,2),
  CREATE_DTTM DATE NOT NULL,
  EMPLOYEE_ID INTEGER NOT NULL,
  DAILY_CLOSE_ID INTEGER,
  ACTUAL_JOB_TYPE_ID INTEGER,
  CREATE_USER_ID INTEGER NOT NULL,
  PRIMARY KEY (EMPLOYEE_SHIFT_ID),
  FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
  FOREIGN KEY (DAILY_CLOSE_ID) REFERENCES DAILY_CLOSE(DAILY_CLOSE_ID),
  FOREIGN KEY (ACTUAL_JOB_TYPE_ID) REFERENCES JOB_TYPE(JOB_TYPE_ID),
  FOREIGN KEY (CREATE_USER_ID) REFERENCES RO_USER(USER_ID),
  UNIQUE (EMPLOYEE_ID, DAILY_CLOSE_ID, ACTUAL_JOB_TYPE_ID)
);

CREATE TABLE EMPLOYEE_SHIFT_INCOME
(
  EMPLOYEE_SHIFT_INCOME_ID SERIAL NOT NULL,
  INCOME_AMT NUMERIC(12,2) NOT NULL,
  EMPLOYEE_SHIFT_ID INTEGER NOT NULL,
  INCOME_FORM_ID INTEGER NOT NULL,
  PRIMARY KEY (EMPLOYEE_SHIFT_INCOME_ID),
  FOREIGN KEY (EMPLOYEE_SHIFT_ID) REFERENCES EMPLOYEE_SHIFT(EMPLOYEE_SHIFT_ID),
  FOREIGN KEY (INCOME_FORM_ID) REFERENCES INCOME_FORM_TYPE(INCOME_FORM_TYPE_ID),
  UNIQUE (EMPLOYEE_SHIFT_ID, INCOME_FORM_ID)
);
